### PR TITLE
Run Openlens builds on PR

### LINKED ISSUE #39: Add test strategy for workflows
Currently, it's not possible to verify the workflow which build lens runs successfully before merge into main.

This results into required reverts in the history, atleast by me.

A proposal would be to enable OpenLens builds on pull requests but exclude the push step on them.

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #39 

It's a proposal

### CODE REVIEW

**Comment by MuhammedKalkan** [comment]
Does not seem to produce artifacts correctly. Only 3 files of which has the same naming as the jobs themselves.  Expecting all produced release assets

**Comment by jkroepke** [comment]
The artifacts are zip archives and contains alls the OpenLens artifacts. 

image

**Comment by MuhammedKalkan** [comment]
That is ok then. i was on mobile and could not check contents

**Review by MuhammedKalkan — APPROVED** [review]
Looking good

**Pull request merged**
