### PR TITLE
Windows builds MSI file

### PR DESCRIPTION
**Pull request by gdlx**
My company needs MSI releases to distribute Windows apps through their software center.
I'm building OpenLens MSI's on my side but maybe you'll want to provide them too.

### CODE REVIEW

**Comment by gdlx** [comment]
Hi @MuhammedKalkan I've just seen the build has failed. This may be related to the signature since it's the only difference with my fork (I had to revert the signature enabling commit on my side).

It is caused by the absence of `WIN_CSC_LINK` env var (and probably `WIN_CSC_KEY_PASSWORD` too) as shown here:
https://github.com/electron-userland/electron-builder/issues/6921#issuecomment-1147397752

I can include them in my PR but I can't test building with signature enabled and you will have to create the matching secrets on your side (not sure if these are the same values than `CSC_LINK`/`CSC_KEY_PASSWORD`).

As you've merged/reverted the PR, do you want me to open it again and try this way ?

**Comment by MuhammedKalkan** [comment]
Other PRs failed that as well. Not sure if it works because they didnt have msi build configed.

I will add those secrets and please open PR. We can give it another shot. If not, i will revert again because i dont really have time to trace it at the moment

**Comment by gdlx** [comment]
I just seen you already have Widnows specific values so I added them in my fork: https://github.com/gdlx/OpenLens/commit/8ae8a78dd8bfc5b5208160401e493d525652066d

Not sure why there are 2 different naming schemes but the build clearly requests `WIN_CSC_LINK`:
```
  ⨯ Env WIN_CSC_LINK is not correct, cannot resolve: D:\a\OpenLens\OpenLens\lens not a file
```

I'll open a PR that way to check if the build works.

**Comment by MuhammedKalkan** [comment]
Yes i am aware of that but strange things  happen when you set a value and 3 different OS es start building with all those values.

**Pull request merged**
