### PR TITLE
Build arm64 on linux

### LINKED ISSUE #33: Add .deb packages for Debian/Ubuntu ARM64
Kindly add .deb packages for Debian/Ubuntu ARM64.
Also include build instructions. 

I have a working build for ARM64 Debian/Ubuntu and can share the details.

### PR DESCRIPTION
**Pull request by jkroepke**
Reverts MuhammedKalkan/OpenLens#38

fixes #33

### CODE REVIEW

**Comment by jkroepke** [comment]
no idea. whats wrong here

**Comment by MuhammedKalkan** [comment]
seems related to this https://github.com/electron-userland/electron-builder/issues/5252

**Comment by jkroepke** [comment]
For unknown reasons, it is three times green in a row now.

**Comment by MuhammedKalkan** [comment]
Lets merge and revert if fails again

**Pull request merged**
