### PR TITLE
Fix latest version check

### LINKED ISSUE #43: Latest version detection
The current workflow uses the official Lens auto-update mechanism (https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml) to detect the latest version.

Since this repo does not depend on official Lens builds, consider to switch the latest version detection based on the git tags on https://github.com/lensapp/lens/

e.g.

```bash
curl -sSfL https://github.com/lensapp/lens/releases.atom | grep -oP "(?<=<title>)v[^<]+" | head -n1
v6.1.0
```
requires gnu grep (may not work in mac os)

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #43 

https://github.com/jkroepke/OpenLens/actions/runs/3091582481/jobs/5001829267

### CODE REVIEW

**Comment by MuhammedKalkan** [comment]
At your branch version file seems to be changed 11 days ago. I was expecting that to get updated aswell with your commit and action process

**Comment by MuhammedKalkan** [comment]
Ok , version file will change when diff happens i think

**Comment by jkroepke** [comment]
Ah, i see.

**Comment by MuhammedKalkan** [comment]
On second look, version is updated at lens repo to 6.1.0. So version file must be updated by check job. Currently it seems not working

**Review by MuhammedKalkan — CHANGES_REQUESTED** [review]
Please add version file change part. You see it in previous yml files as ' > version'
```
curl -s https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml |\
            grep -o "version:.*-latest" | grep -oP "(\d+(:?\.\d+)+)" |\
            head -n 1 > version
          export LENS_VERSION=$(cat version)
          echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
```

**Comment by jkroepke** [comment]
There is already an updated commit.

**Review by MuhammedKalkan — APPROVED** [review]

**Pull request merged**
