### PR TITLE
Revert "Build arm64 on linux"

### PR DESCRIPTION
**Pull request by MuhammedKalkan**
Reverts MuhammedKalkan/OpenLens#45

### CODE REVIEW

**Comment by jkroepke** [comment]
why revert?

**Comment by MuhammedKalkan** [comment]
Build failed

**Comment by jkroepke** [comment]
Did you inspect the logs? 

https://github.com/MuhammedKalkan/OpenLens/actions/runs/3152946455/attempts/1

The error was macos/timeout related and even exists after revert

https://github.com/MuhammedKalkan/OpenLens/actions/runs/3153081353

**Comment by MuhammedKalkan** [comment]
Alright lets see  , mysteriously worked  got me i guess

**Pull request merged**
