### PR TITLE
Add code sign and notarization

### LINKED ISSUE #1: Mac app is not trusted
The mac `.dmg` package can easily be installed by dropping the app into `/Applications`, but then most users won't be able to run it due to lack of trusted signature. Is there a way for the GitHub action to pick up some credential for a Mac developer during build?

### LINKED ISSUE #18: Latest release fails to start on M1 MacBook Air
The 6.0.0 release downloads successfully but fails to start (I tried both replacing and clean reinstall, as well as re-downloading. Same result):

image

I'm not sure how to even start debugging this, but will be happy to help...

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #1 
Fixes #18 

Credentials for code sign
* CSC_LINK: (http url OR base64 encoded p12 file container developer id certificate)
* CSC_KEY_PASSWORD: password for p12 file

Credentials for notarization:
* APPLEID: Apple ID for notarization (need access for App Store Connect)
* APPLEIDPASS: App specific password of the Apple ID

Test Binaries: https://github.com/jkroepke/OpenLens/releases/tag/v6.0.0

Thanks to @xavierLowmiller for providing a code sign certificate

Screenshot for notarization:

Bildschirmfoto 2022-08-02 um 14 57 33

Mention, the code sign certificate has 1 year expiry date and needs to be renewed each year.

### CODE REVIEW

**Comment by MuhammedKalkan** [comment]
I believe secrets are not getting copied from PRs.

**Comment by jkroepke** [comment]
Correct, but I can not expose credentials inside workflows.

**Comment by MuhammedKalkan** [comment]
Yes, need to define them inside this repository as secrets,   if you dont think would not compromise credentials security. Only then we can merge this PR successfully

**Comment by zoispag** [comment]
Make sure that **Send secrets to workflows from fork pull requests.** option is unchecked:

image

**Comment by janhoy** [comment]
Thanks for stepping up @jkroepke. I uploaded my cert and set corresponding repo env vars as secrets (using REST API as GitHub UI won't let you do it unless you are repo owner, but rest api lets you set secrets as contributor).

This is how I uploaded my cert and cert-pw:
```
# Tooling
brew install gh
gh auth login
# Get repo's public key
gh api /repos/MuhammedKalkan/OpenLens/actions/secrets/public-key
# Upload certificate
gh api \
  --method PUT \
  -H "Accept: application/vnd.github.v3+json" \
  /repos/MuhammedKalkan/OpenLens/actions/secrets/MACOS_CERTIFICATE \
  -f encrypted_value='xxxxx' \
  -f key_id='xxxx'
# Upload certificate password
gh api \
  --method PUT \\n  -H "Accept: application/vnd.github.v3+json" \  /repos/MuhammedKalkan/OpenLens/actions/secrets/MAOS_CERTIFICATE_PWD \
  -f encrypted_value='xxxxx' \
  -f key_id='xxxx'
# Check that secrets are now there
gh api -H "Accept: application/vnd.github.v3+json" \                
  /repos/MuhammedKalkan/OpenLens/actions/secrets
```

I had to convert my p12 certificate and password to base64 format to insert in place of 'xxxxx' above.

**Comment by jkroepke** [comment]
Mention that the p12 itself needs base64 format. Even if I manually enter the value through UI. If you have to encode all values with base64 in the API call, you have to encode the p12 file twice.

**Comment by jkroepke** [comment]
@janhoy do you need any assistance?

**Comment by janhoy** [comment]
> @janhoy do you need any assistance?

If you are made a committer on this project you will be able to push your signing cert as a secret like I did. @MuhammedKalkan ?

**Comment by MuhammedKalkan** [comment]
I am waiting for a feedback https://github.com/MuhammedKalkan/OpenLens/pull/21#issuecomment-1202703694
@jkroepke can be made a contributer like you are and define secrets in this repository, if he is ok about security concerns of the account he used

**Comment by MuhammedKalkan** [comment]
Btw, secrets added by a contributor can not be seen, only can be updated. I dont think there will be any security issues.

**Comment by rpardini** [comment]
Very interesting, this. Didn't know contributors could set/reset secrets via API.
Without this, I'd advise you two to exchange age or gpg keys, then transmit the secret material encrypted to the repo owner. 
But if doable via API, even better, since owner does not need to see the material.

Either way: great work 👍, please finish this when possible, I'm really done with building OpenLens myself due to lack of notarization. It would be great to _also_ include a sha256 sum of the final notarized binary in the build logs so we can check it's built from pristine sources.

**Comment by MuhammedKalkan** [comment]
Alright great, in the mean time, i will add you as contributor

**Comment by jkroepke** [comment]
SHA256 sums are now available inside CI.

Secrets are configured now through gh cli

```
gh secret --repo MuhammedKalkan/OpenLens set CSC_LINK --body "***"
gh secret --repo MuhammedKalkan/OpenLens set CSC_KEY_PASSWORD --body "***"
gh secret --repo MuhammedKalkan/OpenLens set APPLEID --body "***"
gh secret --repo MuhammedKalkan/OpenLens set APPLEIDPASS --body "***"
```

**Comment by MuhammedKalkan** [comment]
Seems secrets are defined. İ am merging this for further testing

**Comment by holograph** [comment]
I spend a couple weeks moving house and someone beats me to the punch :-)  Huge kudos @MuhammedKalkan and @jkroepke for picking this up, and thanks from the community!

**Pull request merged**
