### PR TITLE
Windows builds MSI file

### PR DESCRIPTION
**Pull request by gdlx**
Replaces & may fix #74

### CODE REVIEW

**Comment by gdlx** [comment]
Let's hope it builds successfully with the new secrets set but as I can't test on my side, I don't think I'll persist much if it fails.

**Comment by gdlx** [comment]
Has it been automatically merged ?
I wish I could have been able to troublshoot the build a bit...

**Comment by MuhammedKalkan** [comment]
Nope just trying something out. Reopen and work on it if you wish

**Comment by MuhammedKalkan** [comment]
Ok i was right, dont waste time on CSC  error. There is another one related with MSI install. Please check it out.

**Comment by MuhammedKalkan** [comment]
Take a look at this https://github.com/electron-userland/electron-builder/issues/7248

**Comment by gdlx** [comment]
> Take a look at this [electron-userland/electron-builder#7248](https://github.com/electron-userland/electron-builder/issues/7248)

Yes I've seen that one on the main build. Seems to be related to large secrets being stored in environment variables: https://github.com/tauri-apps/tauri/issues/4791#issuecomment-1200523294

Not sure how big the CSC variables are but adding duplicates as we did probably won't help.

Could you tell me which variable may contain noticeably large secrets ? (maybe Apple ones that I could cleanup before running Windows build 🤞)

**Comment by gdlx** [comment]
The comment here sounds interesting: https://stackoverflow.com/a/9722623/1075949
image

**Pull request merged**
