### PR TITLE
Add universal builds for MacOS

### PR DESCRIPTION
**Pull request by jkroepke**
Try comment from https://github.com/MuhammedKalkan/OpenLens/issues/3#issuecomment-1198307197

Reference: https://github.com/electron-userland/electron-builder/issues/5475

### CODE REVIEW

**Comment by MuhammedKalkan** [comment]
Does this produce another binary for macos or just configurational change of the ones produced?

**Comment by jkroepke** [comment]
It will produce an additional binary for arm64. The universal step will merge both binaries into one fat binary. The end result contains both builds including a double file size.

I setup make build locally and check if the paths are still correct.

**Comment by MuhammedKalkan** [comment]
We are renaming binaries to put in assets and latest-mac.yml also uses file names produced to check if a newer version is present. We should check if both are intact for the pipeline

**Comment by jkroepke** [comment]
It seems like the Lens Project is not compatible with electron universal builds. 

Error:

```
{
  uniqueToX64: [
    'Contents/Resources/x64/helm',
    'Contents/Resources/x64/kubectl',
    'Contents/Resources/x64/lens-k8s-proxy'
  ],
  uniqueToArm64: [
    'Contents/Resources/arm64/helm',
    'Contents/Resources/arm64/kubectl',
    'Contents/Resources/arm64/lens-k8s-proxy'
  ]
}
  ⨯ While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds  failedTask=build stackTrace=Error: While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds
    at exports.makeUniversalApp (/Users/jkr/Downloads/lens/node_modules/@electron/universal/src/index.ts:108:13)
    at MacPackager.doPack (/Users/jkr/Downloads/lens/node_modules/app-builder-lib/src/macPackager.ts:125:9)
    at MacPackager.pack (/Users/jkr/Downloads/lens/node_modules/app-builder-lib/src/macPackager.ts:191:7)
    at Packager.doBuild (/Users/jkr/Downloads/lens/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/jkr/Downloads/lens/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/jkr/Downloads/lens/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/jkr/Downloads/lens/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/jkr/Downloads/lens/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
```

It seems like Lens is put the binaries into different path which is not expected by electron-builder. And I do not see a toggle to disable this behaivor.

https://github.com/electron/universal/blob/3a30fe989bee57d93b3da7beb9e9bf8ca29639fc/src/index.ts#L114

**Comment by NotANormalNerd** [comment]
I have it checked out on my machine (M1 MBP) and I just added the --universal flag to the original project. Made a `make build` and it worked without a problem. I was also thinking of just adding a PR for the upstream project.

**Comment by jkroepke** [comment]
Where you added the universal flag?

**Comment by NotANormalNerd** [comment]
I rechecked and it did actually not work because the build:mac is never called, but as far as I see we found a solution nonetheless, which works. (separate binaries for x86 and arm64).

**Pull request closed without merging**
